### ISSUE TITLE
Anyway to modify returned status code?

### ISSUE THREAD

**Issue by kbohinski** [bahlo/goat#11]
I would like to return a `429 Too Many Requests` and a `500 Internal Server Error` conditionally. Is there anyway to do this?

**Comment by bahlo** [comment]
You can easily set an error code via [WriteJSONWithStatus](https://godoc.org/github.com/bahlo/goat#WriteJSONWithStatus) 😁

**Comment by kbohinski** [comment]
Oh sorry! Did not see the godoc link! 😆

**Comment by bahlo** [comment]
No problem, feel free to ask if you run into problems. And I'd be glad to hear what you use it for 👍
