### ISSUE TITLE
Content-Type of goat.WriteError not application/json

### ISSUE THREAD

**Issue by zwerch** [bahlo/goat#4]
Somehow `goat.WriteError`seems to not set the `Content-Type`-header correctly to `application/json`.

Could you verify this?

**Comment by bahlo** [comment]
Hey @zwerch,

I think it's the `w.WriteHeader()` method [here](https://github.com/bahlo/goat/blob/master/json.go#L10), which permits the change of headers afterwards.

A solution could be to write a private method which writes and takes an error code and a JSON interface.
This way `WriteError` and `WriteJSON` could access that method and we'd have no duplicate header writes.

**Comment by bahlo** [comment]
Fixed in [`1.0.7`](https://github.com/bahlo/goat/commit/4de72452b8cfe7dc1dd9acabf3ca8d4d443dd1ad).
